name: CI/CD Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: 13.48.133.135
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # 1. כניסה ומשיכת קוד
            cd /home/ubuntu/Dream/Dream
            git pull
            
            # 2. כניסה עמוקה לבנייה
            cd Dream/client
            npm install
            npm run build
            
            # 3. העתקה מתוך תיקיית ה-dist שנוצרה הרגע
            # שימי לב: הנתיב הוא ~/Dream/Dream/Dream/client/dist/
            sudo rm -rf /var/www/html/*
            sudo cp -r /home/ubuntu/Dream/Dream/client/dist/* /var/www/html/
            
            # 4. רענון
            sudo systemctl restart node-service
            sudo systemctl restart nginx
